name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Lint
        run: poetry run ruff check src/sudoku_nisq/
      - name: Type Check
        run: poetry run mypy src/sudoku_nisq/
      - name: Run tests
        run: poetry run pytest --cov=src/sudoku_nisq tests/
